server:
  port: 18000
  servlet:
    context-path: /auth

spring:
  application:
    name: service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: dev
      config:
        namespace: dev
        group: dev
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      eager: true
  config:
    import:
    - nacos:service-auth.yml

#  # 分片规则配置 (分表)
#  shardingsphere:
#    datasource:
#      names: chair
#      chair:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://127.0.0.1:3306/chair?allowPublicKeyRetrieval=true&useSSL=false
#        username: root
#        password: 123456
#    rules:
#      sharding:
#        # 分片算法配置
#        shardingAlgorithms:
#          # 自定义分片规则名
#          answer-table-inline:
#            ## inline 类型是简单的配置文件里面就能写的类型，其他还要自定义类
#            type: INLINE
#            props:
#              algorithm-expression: user_answer_${appId % 2}
#        tables:
#          user_answer:
#            actualDataNodes: chair.user_answer_${0..1}
#            # 分表策略
#            table-strategy:
#              standard:
#                sharding-column: appId
#                sharding-algorithm-name: answer-table-inline

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 微信相关
#wx:
#  # 公众号配置
#  mp:
#    configs:
#      - appId: wxc35350dbd6614a48
#        secret: f42e491be945c87e5d9e769baa044c1d
#        token: asjdkhuqnjk741
#        aesKey: 5FSIj6N1pA45G5oMvMWF9yDE564e7ikmum3hjWzWfWK
#  # 小程序配置
#  ma:
#    configs:
#      - appId: wx9a14dc66b49b6ad2
#        secret: 730a5de454eb7a8e8d6f78eaabb93c32
#        # 微信支付商户号，请去微信支付平台申请
#        mchId: xxxxxxxx
#        # 微信支付商户APIv2密钥，请去微信支付平台申请
#        mchKey: xxxxxxxxxxxxxxxxxxxxx
#        # p12证书的位置，绝对路径
#        keyPath: /mnt/install/joolun-wx/apiclient_cert.p12

# 接口文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.chair.auth.controller

# knife4j config
knife4j:
  enable: true
  setting:
    language: zh-CN

chair:
  token-name: chair-token