server:
  port: 18010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        group: dev
    gateway:
       routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://service-auth # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
          - Path=/auth/**
        - id: order-service # 路由id，自定义，只要唯一即可
          uri: lb://service-ai
          predicates:
          - Path=/ai/**